#!/bin/sh

# TODO: file needs to be fixed
___BUILDCMD="$*"
jq -n --arg cmd "$___BUILDCMD" --arg pwd "$PWD" --arg file "$PWD/main.cpp" '[.[0]|.command=$cmd|.directory=$pwd|.file=$file]' > compile_commands.json
